### PR TITLE
Inline pseudo elements

### PR DESCRIPTION
**Pull request by parshap**
This adds support for "inlining" pseudo elements (`::before` and `::after` selectors) into the document as `<span>` elements.

Tests for this behavior are added in `test/cases/pseudo-elements.*`.

### CODE REVIEW

**Comment by parshap** [comment]
@jrit, @rauchg: Any thoughts on this change? I'd like to get this in so that I can move off of my juice fork and back on upstream. I'm happy to update this against current master if it's a wanted change.

**Comment by jrit** [comment]
For sure, there should be an option to turn this on/off. Outside that, I wonder if it would make more sense to have a specific `juice.inlinePseudos()` that encapsulates all this and can be used when options calls for it. It just strikes me as getting more into rewriting the DOM than inlining CSS in a way and I can think of other rewrite utilities that I wouldn't necessarily weave into the core of the CSS inliner. Not sure how practical it is to pull it out, but that is where my thinking is.

**Comment by parshap** [comment]
I'm not sure it should be an option. That would be similar to having an option for if padding is inlined or not. I understand it's a bit different adding elements to the dom compared to modifying existing elements' attributes, but if it results in the same visual appearance as what the original css would have produced, I don't think it matters. In this case, a CSS pseudo element and an actual element in the dom are the exact same thing as far as the browser rendered is concerned.

I think the question is about the goal of juice. For me, the goal is to take some html+css and produce html-only that will result in browsers computing the same render tree as the html+css would have produced.

I don't think there should be a bunch of options that users have to think about, I think it should *just work*.

**Comment by jrit** [comment]
The DOM manipulation can cause some conflict with media queries. For example, if the inlined style has a certain contents or style that should be normally overriden by a media query that is preserved, then that may no longer work if the pseudos are in new elements. There is also the potential that selectors like `:last-child` would then apply to the inserted elements instead of the elements they were originally meant to target.

**Comment by parshap** [comment]
> The DOM manipulation can cause some conflict with media queries. For example, if the inlined style has a certain contents or style that should be normally overriden by a media query that is preserved, then that may no longer work if the pseudos are in new elements.

I don't quite follow this example.

> There is also the potential that selectors like :last-child would then apply to the inserted elements instead of the elements they were originally meant to target.

`:last-child` selectors will work out fine because styles are calculated before the pseudo elements are inserted into the dom. I've added tests for this case.

Anyway, I'm not against having it behind a flag, just want to avoid it unless it's necessary. I think inlining pseudo elements will result in more corrected pages than broken pages. For example, most "clearfix" implementations use pseudo elements.

Let me know what you guys want to do and I'll update it against master and add a flag if wanted.

**Comment by jrit** [comment]
Sorry if I was unclear. What I mean about media queries and also `:last-child` is that in responsive emails that I inline I will use `preserveMediaQueries` so that on smaller screens those media query styles (which are not inlined) are applied to the DOM. My point is that if you make modifications to the original DOM then when the media queries are applied to the inlined DOM, some of the selectors can end up pointing at different elements than they would have in the original DOM. So these options don't work reliably together, and thus there is a need for the flag.

**Comment by parshap** [comment]
@jrit fair enough! I've updated against current master and put it behind the `inlinePseudoElements` option (defaults to`false`). Do you think any other changes are needed?

**Comment by jrit** [comment]
spaces after `!` seems out of place for the project, but otherwise looks good to me

**Comment by parshap** [comment]
Oops, personal style habit. Fixed.

**Comment by parshap** [comment]
@jrit what do you think about getting this merged?

**Comment by jrit** [comment]
I'm going to take a look at them soon. Just have to make sure the builds still pass on those diffs. Do you want to close #92 ? Seems unnecessary now.

**Comment by parshap** [comment]
I merged in upstream master - tests pass and the only conflict was in `History.md`.

**Comment by jrit** [comment]
@parshap apparently there is a conflict with your other merged PR, just pull/resolve/push again.

**Comment by parshap** [comment]
@jrit yep that was expected. I've merged master and resolved conflicts. This should be ready to go now.

**Pull request merged**
