### PR TITLE
fix: pin cheerio to latest rc.12

### PR DESCRIPTION
**Pull request by cossssmin**
Fixes issues with breaking changes from `cheerio@1.0.0` until it's handled somehow upstream.

See [discussion](https://github.com/cheeriojs/cheerio/issues/3993) for more info.

### CODE REVIEW

**Comment by cossssmin** [comment]
Related: https://github.com/Automattic/juice/issues/493

**Comment by cossssmin** [comment]
@jrit could you please have a look at this? It's currently breaking for many users because of cheerio: either because of Node 18 requirement or in other cases `&` is converted to `&amp;` because of how they also changed [htmlparser2 options](https://github.com/cheeriojs/cheerio/pull/2916).

We need to release a patch that pins cheerio until they resolve this entire debacle.

**Review by jrit — APPROVED** [review]
makes sense

**Comment by jrit** [comment]
@cossssmin can I give you publish permissions for juice on npm? what's your username there?

**Comment by cossssmin** [comment]
Sure, I’m `cossssmin` there too:

https://www.npmjs.com/~cossssmin

**Comment by ainsly** [comment]
Just a quick appreciation post for addressing this quickly. Was tough to narrow down which package was actually causing that strange issue that popped up out of nowhere. Kudos 👏 🎉 

All my &zwj; and other html entities suddenly started appearing fulltext in my email templates. Time to add more tests...

**Pull request merged**
