### PR TITLE
Add support for counters and multiple values in pseudo-elements

### LINKED ISSUE #256: CSS counters is not supported
My Input is 

```
<style>
body {
    counter-reset: section;
}
h2::before {
    counter-increment: section;
    content:counter(section);
}
</style>
<h2> Title 1</h2>
<h2> Title 2</h2>

```

Juice output

image

I hope Juice output

```
<h2><span>1</span> Title 1</h2>
<h2><span>2</span> Title 2</h2>
```

### PR DESCRIPTION
**Pull request by mikevoets**
Adds support for `<var>` `<attr>` `<counter>` in content attributes for pseudo-elements. Also adds the possibility of defining counter-reset and counter-increment in styles.

Fixes #256.

### CODE REVIEW

**Comment by jrit** [comment]
wow, super cool @mikevoets 

could you update the docs with basic info on what you enabled here? sorry I didn't notice this sooner!

**Comment by mikevoets** [comment]
@jrit Glad you think it's cool!

I assumed being able to use `count`, `var` and `attr` worked "out of the box", which is the reason why I haven't updated any documentation. Where in the documentation would it be appropriate to clarify this functionality?

**Comment by jrit** [comment]
sorry I keep missing notifications on this! I merged what you had so far, I guess that is a good point, when I make a release I'll add it to the changelog. thanks again, and sorry for taking so long to notice things :)

**Comment by guanpengchn** [comment]
what a good day! expect the release version!

**Comment by guanpengchn** [comment]
@mikevoets could you tell me how to use this feature？

**Comment by mikevoets** [comment]
@guanpengchn Sorry for the late reply.

It works like this. If you have the following input:


```
<style>
body {
    --foo: 'Bar';
    counter-reset: section;
}
h2::before {
    counter-increment: section;
    content: counter(section);
}
h3::before {
    content: var(--foo) ' - ' attr(data-name);
}
</style>
<h2> Title 1</h2>
<h3 data-name="Baz"> Title 2</h3>
<h2> Title 3</h2>
```
This resolves to:
```
<h2><span>1</span> Title 1</h2>
<h3 data-name="Baz"><span>Bar - Baz</span> Title 2</h3>
<h2><span>2</span> Title 3</h2>
```

**Pull request merged**
