### PR TITLE
add option insertPreservedExtraCss

### LINKED ISSUE #188: Preserve media-queries provided via extraCss
When using `extraCss` to provide CSS with media-queries those won't be inlined i.e. preserved at all. Is there a way to somehow preserve media-queries provided via `extraCss`?

### PR DESCRIPTION
**Pull request by jrit**
Fixes #188 @thasmo

Let me know if you see any issues here.

I've been trying to maintain backward compatibility on the option defaults in 1.x and it is getting sort of annoying now. I think there needs to be a 2.0 soon that changes the defaults for the options to be more sensible. Too much is turned off by default.

### CODE REVIEW

**Comment by thasmo** [comment]
Thanks for implementing this! What do you think about a more fine-grained control about where the CSS gets inserted. Maybe an option for defining a selector and a position. (e.g. `extraCssSelector: head` and `extraCssPosition: append` etc.)

I got a use-case where I want to preserve media-queries in the head, but if there's no head, the media-queries should not be preserved at all.

Maybe that's for another feature/PR?!

Thanks!

**Comment by jrit** [comment]
`insertPreservedExtraCss` could accept `true`, `false` or a string for a CSS selector, but I think it should append in all cases, I can't think of where it would be technically necessary to prepend, and currently the position of `extraCss` as a virtual CSS document, is as appended.

**Comment by jrit** [comment]
I'm thinking the value of `true` is the current behavior in the PR, where it is going to try `head`, then `body`, then just append to the document root.

**Comment by thasmo** [comment]
Sounds good. :)

**Comment by jrit** [comment]
@thasmo look right to you now?

**Comment by thasmo** [comment]
Looks good. Awesome! :)

**Pull request merged**
