### PR TITLE
Add extra css option to cli

### PR DESCRIPTION
**Pull request by calebmer**
Being able to set the `extraCss` option is a required feature of the cli for the work I am doing. So I added that option. Also I setup infrastructure for future async operations before the 'juicing'. By performing `waitingOn++` the `doJuice` function will wait until the `next` function is called before executing. This allows us to fetch dependencies like css files. Also I cleaned up the code by adding a `handleError` function which returns true if there is an error allowing the developer to exit the block.

### CODE REVIEW

**Comment by jrit** [comment]
Are you able to add a test case for the CLI? We don't have any in the project right now.

**Comment by calebmer** [comment]
I could, it didn't seem necessary to me for all of two features, and because there aren't many standard solutions for testing a CLI so I would have to throw something together. If you want I could take the time to make something.

**Comment by jrit** [comment]
The request for coverage isn't a comment about your PR or quality at all, simply that there is currently no test coverage for the CLI. Because we don't have coverage, we don't have a good definition of what constitutes a breaking change to the CLI, and core code changes that might break the CLI go undetected. If you are up for it, it would be super helpful. This PR is a good addition either way.

**Comment by calebmer** [comment]
Ok, added the tests. I added two new cases to use in testing the cli:
- an integration case which uses a basic email template found [here](https://github.com/leemunroe/responsive-html-email-template)
- a case where the css is in the header

A couple of things to note about the tests:
- it expects the cwd to be the root repo directory (this should be the case every time)
- it creates a `tmp` directory at the project root where the cli outputs files. The directory is in the `.gitignore` so it should never be pushed to the repo

For that second point, there are a couple of stylistic choices you can make:
- you can put the `tmp` directory anywhere if you would rather it be `test/tmp` or `.tmp` I could change that
- whether or not the directory is removed upon test completion. Currently it is not but because it is in the `.gitignore` it isn't a huge deal. Removing it would require a dependency, but leaving it allows for better debugging

Thanks for your interest in the pull request and thanks for maintaining the project :smile:

**Comment by jrit** [comment]
This looks great. Thanks so much. I'll publish a release soon.

**Pull request merged**
