### PR TITLE
Move lib/juice.js to index.js

### PR DESCRIPTION
**Pull request by parshap**
Removes unnecessary indirection of `index.js`. It's a pet peeve of mine when I open `index.js` only to see I actually need to be looking at a different file.

### CODE REVIEW

**Comment by parshap** [comment]
Just realized this is going to conflict with the pseudo elements pr once that gets merged - so if we want this change I can rebase after.

**Comment by jrit** [comment]
To me, this seems unnecessary, and if someone does have a fork that they want to merge in later, it is going to create all sorts of confusion about what has changed.

**Comment by Andersos** [comment]
What about adding the `"main"` field in `package.json` then the `index.js` file can be removed. Will that make it better @parshap ?

**Comment by jrit** [comment]
Yeah, I agree, the `main` field should just be updated, that is a much smaller diff. Any reason not to do that?

**Comment by jrit** [comment]
closing as resolved by #124 and published in 1.1.2

**Pull request closed without merging**
