### PR TITLE
bump version to v1.0.1, update history, update rest of tests to mocha

### LINKED ISSUE #108: Improve "Error: Local file not found" message
When migrating from v0.5 to v1.0 I got that error message when calling `juiceResources()` and have no idea what's wrong here.

Any chance this error message could tell a bit more? What local file it is referring to?

Basically I am figuring out how to migrate from `juice.juiceContent(html, options, cb)` to `juice.juiceResources(html, options, cb)` ...

### PR DESCRIPTION
**Pull request by jrit**
@rauchg sorry version wasn't in last PR

Also updated the rest of the tests to use mocha so they will be run with `npm test` and on travis. Fixes #93 
fixes #108

### CODE REVIEW

**Comment by parshap** [comment]
:+1: for tests!

Can we also delete the `Makefile` so there's no confusion about how to run tests?

**Comment by jrit** [comment]
makefile removed

**Comment by davisford** [comment]
Hi, any chance we can get this merged?  I've been banging my head against the wall since I last upgraded a whole bag of dependencies, most notably Juice which seems to have changed the way it deals with paths in a breaking change way since the older version.  I've been fighting with failing tests, and I realized that if I manually force `web-resource-inliner@1.1.0` nested deep in my dep stack, it resolves the issues I was seeing.

But juice hasn't been pushed to npm yet, and still contains the older `web-resource-inliner@1.0.1`.

**Comment by davisford** [comment]
Thanks for merging it @rauchg -- would love to see it pushed to npm :+1:

**Comment by binarykitchen** [comment]
Yes, please npm-publish this, thx @jrit

**Pull request merged**
