### PR TITLE
Sort properties by selector specificity

### PR DESCRIPTION
**Pull request by parshap**
This change adds the failing test case from #51 and then fixes it.

Sorting the properties by their selector's specificity makes properties that affect each other (e.g., "padding" and "padding-bottom") work as expected.

Other tests' expected results had to be updated to change the property order.

### CODE REVIEW

**Comment by jrit** [comment]
This may already be fixed in an unreleased version based on the alphabetizing of styles. Can you confirm?

**Comment by parshap** [comment]
@jrit which unreleased version are you referring to? The current master branch? If so, then no it is not resolved. Sorting alphabetically is *not* the right way to do it - we need to sort by the selector's specificity. This is important in achieving the same computed styles with inline styles as would have resulted with the original CSS.

PS: I'm happy to update my PRs with current master so they can be merged automatically, but first lets decide which ones should be merged in.

**Comment by jrit** [comment]
Yeah, master. And you seem to be correct that your version of the sorting should be better than what is in there currently. Thanks for checking.

**Comment by parshap** [comment]
@jrit, @rauchg: Any thoughts on this change? I can update against current master if we want it.

**Comment by jrit** [comment]
This makes sense to me

**Comment by parshap** [comment]
This will also resolve #48.

**Comment by parshap** [comment]
Merged upstream master and fixed two newly added tests to have the correct property order.

**Comment by jrit** [comment]
Thanks @parshap - will bundle into next release soon

**Pull request merged**
