### PR TITLE
Upgrade to cheerio v1

### PR DESCRIPTION
**Pull request by TrySound**
This version of cheerio already 1 year published with latest tag.

Here are changes
https://github.com/cheeriojs/cheerio/blob/v1.0.0-rc.3/History.md#100-rc2--2017-07-02

### CODE REVIEW

**Comment by TrySound** [comment]
I'm not TS user. Could you assist me how to solve errors?

**Comment by jrit** [comment]
> I'm not TS user. Could you assist me how to solve errors?

I'm not either. All the TS commits were made by other contributors that were

**Comment by TrySound** [comment]
Got it. Very old typescript version 😀

**Comment by jrit** [comment]
@TrySound thanks for all the updates. In case it wasn't obvious, just waiting until you feel things are done before I make releases

**Comment by TrySound** [comment]
I think I'm done with web-resource-inliner. You can make a release. Will upgrade it and commander in juice.

**Pull request merged**
