### PR TITLE
Fixed cheerio version

### PR DESCRIPTION
**Pull request by DeepVince**
Fixed cheerio version to stop breaking changes in its latest version `1.0.0-rc.11`

### CODE REVIEW

**Comment by alagane** [comment]
Shouldn't you also modify the `package-lock.json` file?

**Comment by wuranxu** [comment]
please merge the code 😢

**Comment by francois06** [comment]
bump, cannot use in nodejs anymore

**Comment by francois06** [comment]
**Meanwhile, here my fix :** 

if you use yarn, add these lines in package.json : 
```
 "resolutions": {
    "cheerio": "1.0.0-rc.10",
    "parse5-htmlparser2-tree-adapter": "^6.0.0"
}
```

if you use npm, add these lines in package.json : 
```
 "overrides": {
    "cheerio": "1.0.0-rc.10",
    "parse5-htmlparser2-tree-adapter": "^6.0.0"
}
```


Ressources
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/


My original post on cheerio 

https://github.com/cheeriojs/cheerio/issues/2545#issuecomment-1154105281

**Pull request merged**
