### PR TITLE
Refactored code to better "isolate" cheerio dependency and enable jquery usage

### PR DESCRIPTION
**Pull request by bago**
This is better reviewed as a commit-by-commit changes because a lot of code has been moved between files (from utils.js to cheerio.js and from client.js to lib/inline.js).

Refactoring let me isolate cheerio so that one can include "lib/inline.js" and use core juice features without including cheerio.

The real "changes" are the use of ".attr('data-embed')" instead of ".attribs['data-embed']" and the introdution of a "options.styleAttributeName" to change the attribute when the inline styles are read/written.

### CODE REVIEW

**Comment by bago** [comment]
Please note that the only real change I need in order to integrate with Mosaico is https://github.com/Automattic/juice/pull/223/commits/96ec50ab48ca32dcab40056764fd787367a8b304 

The other tasks make it only easier and cleaner to do that and I don't have to create "subtle" tricks in order to avoid cheerio being included.

Now I'm starting to work on Mosaico side and this branch, so to see if this really work as I expect.

**Comment by jrit** [comment]
Lot of refactoring, but looks all green on the tests, so good for me so far. Let me know how your tests go.

**Comment by bago** [comment]
Integration with mosaico worked: https://github.com/voidlabs/mosaico/blob/master/src/js/ext/inliner.js

**Comment by jrit** [comment]
@bago do you want to make a release for the bower change on mensch so the dependency here can be a version instead of git hash? The rest is looking good to merge. Are you going to work on more issues before there should be a release of Juice?

**Comment by bago** [comment]
Hi @jrit 

I think I should at least sort the code in "getPreservedText" so to keep only "method2" (the one that is more similar to the current behaviour).

Also I don't know if I should keep the "hacks" to make the output spacing similar to the old one or, now that we know the tests pass, we should simply remove the hacks and update the tests to expect the new spacings.

Abount mensch release I'm investigating a minor bug in mensch (it doesn't affect juice directly), I hope I can do this the next week and then make a new release (unfortunately I only have karma for github and I can't do the NPM release for it)

For the record the problem in mensch is about the way ".selector { color:: red; }" (note the weird "::") is parsed and the way mensch tells you that "color" is ":red" (lost space between : and red). I have to read the CSS specification to understand what is the rigth way to parse that kind of potentially malformed code. In fact I don't expect that pattern to be used by anyone (it was part of an old test I wrote to test parsers behaviours), so if I can't find the time to check this I'll make the mensch release "as is" so we can complete this "merge".

Thank you,
Stefano

**Comment by jrit** [comment]
@bago did you get a chance to make that release or maybe fix the mensch issue? Would like to merge this, sorry about my delayed response.

**Comment by bago** [comment]
@jrit thank your from bringing this up... I was lost on daily routine and this issue slept away. I just fixed the mensch issue I wanted to fix (brettstimmerman/mensch#21) and made a [v0.3.3 release](https://github.com/brettstimmerman/mensch/releases/tag/v0.3.3) including bower declaration.

I cleaned up the getPreservedText method and updated tests according to spacing/newlines changes that was there only in the css parser migration "phase".

I'm sorry I won't have time soon to work on other juice issues, but let me know if I can do anything in order to have a new juice release including my changes.

**Comment by bago** [comment]
PS: unfortunately I don't have karma to make an npm release for mensch, so I guess we have to keep the "github" reference in package.json. At least we now reference a specific version instead of an hash.

**Comment by jrit** [comment]
Thanks so much for all your work @bago

**Pull request merged**
